[versions]
kotlin = "1.7.0"
fabric-loom = "0.12-SNAPSHOT"

[libraries]
minecraft = "com.mojang:minecraft:1.19"
yarn = "net.fabricmc:yarn:1.19+build.4"
fabric = "net.fabricmc.fabric-api:fabric-api:0.56.0+1.19"
fabric-loader = "net.fabricmc:fabric-loader:0.12-SNAPSHOT"
fabric-kotlin = "net.fabricmc:fabric-language-kotlin:1.8.0+kotlin.1.7.0"
